/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as KeranjangRouteImport } from './routes/keranjang'
import { Route as NotifikasiRouteImport } from './routes/notifikasi'
import { Route as PesananRouteImport } from './routes/pesanan'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PusatRouteImport } from './routes/pusat'
import { Route as StandarKurasiRouteImport } from './routes/standar-kurasi'
import { Route as KoperasiIndexRouteImport } from './routes/koperasi.index'
import { Route as KoperasiIdRouteImport } from './routes/koperasi.$id'
import { Route as ProdukIdRouteImport } from './routes/produk.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const KeranjangRoute = KeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => rootRouteImport,
} as any)
const NotifikasiRoute = NotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananRoute = PesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PusatRoute = PusatRouteImport.update({
  id: '/pusat',
  path: '/pusat',
  getParentRoute: () => rootRouteImport,
} as any)
const StandarKurasiRoute = StandarKurasiRouteImport.update({
  id: '/standar-kurasi',
  path: '/standar-kurasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KoperasiIndexRoute = KoperasiIndexRouteImport.update({
  id: '/koperasi/',
  path: '/koperasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoperasiIdRoute = KoperasiIdRouteImport.update({
  id: '/koperasi/$id',
  path: '/koperasi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIdRoute = ProdukIdRouteImport.update({
  id: '/produk/$id',
  path: '/produk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/keranjang': typeof KeranjangRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRoute
  '/profil': typeof ProfilRoute
  '/pusat': typeof PusatRoute
  '/standar-kurasi': typeof StandarKurasiRoute
  '/koperasi/$id': typeof KoperasiIdRoute
  '/produk/$id': typeof ProdukIdRoute
  '/koperasi/': typeof KoperasiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/keranjang': typeof KeranjangRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRoute
  '/profil': typeof ProfilRoute
  '/pusat': typeof PusatRoute
  '/standar-kurasi': typeof StandarKurasiRoute
  '/koperasi/$id': typeof KoperasiIdRoute
  '/produk/$id': typeof ProdukIdRoute
  '/koperasi': typeof KoperasiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/keranjang': typeof KeranjangRoute
  '/notifikasi': typeof NotifikasiRoute
  '/pesanan': typeof PesananRoute
  '/profil': typeof ProfilRoute
  '/pusat': typeof PusatRoute
  '/standar-kurasi': typeof StandarKurasiRoute
  '/koperasi/$id': typeof KoperasiIdRoute
  '/produk/$id': typeof ProdukIdRoute
  '/koperasi/': typeof KoperasiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/keranjang'
    | '/notifikasi'
    | '/pesanan'
    | '/profil'
    | '/pusat'
    | '/standar-kurasi'
    | '/koperasi/$id'
    | '/produk/$id'
    | '/koperasi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/keranjang'
    | '/notifikasi'
    | '/pesanan'
    | '/profil'
    | '/pusat'
    | '/standar-kurasi'
    | '/koperasi/$id'
    | '/produk/$id'
    | '/koperasi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/keranjang'
    | '/notifikasi'
    | '/pesanan'
    | '/profil'
    | '/pusat'
    | '/standar-kurasi'
    | '/koperasi/$id'
    | '/produk/$id'
    | '/koperasi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  KeranjangRoute: typeof KeranjangRoute
  NotifikasiRoute: typeof NotifikasiRoute
  PesananRoute: typeof PesananRoute
  ProfilRoute: typeof ProfilRoute
  PusatRoute: typeof PusatRoute
  StandarKurasiRoute: typeof StandarKurasiRoute
  KoperasiIdRoute: typeof KoperasiIdRoute
  ProdukIdRoute: typeof ProdukIdRoute
  KoperasiIndexRoute: typeof KoperasiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keranjang': {
      id: '/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof KeranjangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifikasi': {
      id: '/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof NotifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan': {
      id: '/pesanan'
      path: '/pesanan'
      fullPath: '/pesanan'
      preLoaderRoute: typeof PesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pusat': {
      id: '/pusat'
      path: '/pusat'
      fullPath: '/pusat'
      preLoaderRoute: typeof PusatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standar-kurasi': {
      id: '/standar-kurasi'
      path: '/standar-kurasi'
      fullPath: '/standar-kurasi'
      preLoaderRoute: typeof StandarKurasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koperasi/': {
      id: '/koperasi/'
      path: '/koperasi'
      fullPath: '/koperasi/'
      preLoaderRoute: typeof KoperasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koperasi/$id': {
      id: '/koperasi/$id'
      path: '/koperasi/$id'
      fullPath: '/koperasi/$id'
      preLoaderRoute: typeof KoperasiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$id': {
      id: '/produk/$id'
      path: '/produk/$id'
      fullPath: '/produk/$id'
      preLoaderRoute: typeof ProdukIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  KeranjangRoute: KeranjangRoute,
  NotifikasiRoute: NotifikasiRoute,
  PesananRoute: PesananRoute,
  ProfilRoute: ProfilRoute,
  PusatRoute: PusatRoute,
  StandarKurasiRoute: StandarKurasiRoute,
  KoperasiIdRoute: KoperasiIdRoute,
  ProdukIdRoute: ProdukIdRoute,
  KoperasiIndexRoute: KoperasiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
